# vocab_data.py

MEGA_VOCAB = [
    # === 一、排练指令与指挥口头禅 ===
    {"word": "iniziare", "meaning": "开始", "pos": "v."},
    {"word": "da capo", "meaning": "从头开始", "pos": "adv."},
    {"word": "dall'inizio", "meaning": "从最开始处", "pos": "adv."},
    {"word": "riprendere", "meaning": "重新开始 / 接着唱", "pos": "v."},
    {"word": "ricominciare", "meaning": "重新开始", "pos": "v."},
    {"word": "continuare", "meaning": "继续", "pos": "v."},
    {"word": "fermarsi", "meaning": "停止", "pos": "v."},
    {"word": "stop", "meaning": "停", "pos": "int."},
    {"word": "ancora", "meaning": "再 / 再次", "pos": "adv."},
    {"word": "ancora una volta", "meaning": "再来一次", "pos": "phrase"},
    {"word": "un'altra volta", "meaning": "再一次", "pos": "phrase"},
    {"word": "ripetere", "meaning": "重复", "pos": "v."},
    {"word": "attenzione", "meaning": "注意", "pos": "n."},
    {"word": "ascoltare", "meaning": "听", "pos": "v."},
    {"word": "guardare", "meaning": "看", "pos": "v."},
    {"word": "seguire", "meaning": "跟随 / 看指挥", "pos": "v."},
    {"word": "osservare", "meaning": "观察", "pos": "v."},
    {"word": "lento", "meaning": "慢的", "pos": "adj."},
    {"word": "veloce", "meaning": "快的", "pos": "adj."},
    {"word": "accelerare", "meaning": "加速", "pos": "v."},
    {"word": "accelerando", "meaning": "渐快", "pos": "adv."},
    {"word": "rallentare", "meaning": "减速", "pos": "v."},
    {"word": "ritardando", "meaning": "渐慢", "pos": "adv."},
    {"word": "ritardare", "meaning": "渐慢 / 延迟", "pos": "v."},
    {"word": "mantenere", "meaning": "保持", "pos": "v."},
    {"word": "a tempo", "meaning": "回原速", "pos": "phrase"},
    {"word": "tempo", "meaning": "节奏 / 拍子 / 速度", "pos": "n."},
    {"word": "battito", "meaning": "拍子", "pos": "n."},
    {"word": "pulsazione", "meaning": "脉动 / 基拍", "pos": "n."},
    {"word": "levare", "meaning": "弱拍 / 抬手拍 (吸气拍)", "pos": "n."},
    {"word": "battere", "meaning": "强拍 / 落手拍", "pos": "n."},
    {"word": "sincronia", "meaning": "同步 / 一致", "pos": "n."},
    {"word": "piano", "meaning": "弱", "pos": "adj./adv."},
    {"word": "pianissimo", "meaning": "极弱", "pos": "adj./adv."},
    {"word": "forte", "meaning": "强", "pos": "adj./adv."},
    {"word": "fortissimo", "meaning": "极强", "pos": "adj./adv."},
    {"word": "crescendo", "meaning": "渐强", "pos": "adv."},
    {"word": "diminuendo", "meaning": "渐弱", "pos": "adv."},
    {"word": "mezzoforte", "meaning": "中强", "pos": "adj./adv."},
    {"word": "mezzopiano", "meaning": "中弱", "pos": "adj./adv."},
    {"word": "legato", "meaning": "连音", "pos": "adj./adv."},
    {"word": "staccato", "meaning": "断音", "pos": "adj./adv."},
    {"word": "marcato", "meaning": "强调 / 加重", "pos": "adj./adv."},
    {"word": "sostenuto", "meaning": "持续的", "pos": "adj./adv."},
    {"word": "espressivo", "meaning": "有表现力的", "pos": "adj."},
    {"word": "con espressione", "meaning": "富有表情地", "pos": "phrase"},
    {"word": "cantabile", "meaning": "如歌地", "pos": "adj./adv."},
    {"word": "più forte", "meaning": "更响", "pos": "phrase"},
    {"word": "più piano", "meaning": "更轻", "pos": "phrase"},
    {"word": "dal segno", "meaning": "从记号处反复", "pos": "phrase"},
    {"word": "prova", "meaning": "排练 / 试验", "pos": "n."},
    {"word": "prova generale", "meaning": "总排练 / 彩排", "pos": "n."},
    {"word": "marcare", "meaning": "标记 (排练时不发全音量唱)", "pos": "v."},
    {"word": "mezza voce", "meaning": "半声 / 轻声", "pos": "n."},
    {"word": "insieme", "meaning": "一起", "pos": "adv."},
    {"word": "all'unisono", "meaning": "齐唱 / 齐奏", "pos": "phrase"},
    {"word": "anticipare", "meaning": "抢拍 / 提前", "pos": "v."},
    {"word": "ritardare il tempo", "meaning": "拖拍", "pos": "phrase"},
    {"word": "andare a tempo", "meaning": "跟上节奏", "pos": "phrase"},
    {"word": "fuori tempo", "meaning": "不合拍子 / 错拍", "pos": "phrase"},
    {"word": "attaccare", "meaning": "切入 / 进点 / 起唱", "pos": "v."},
    {"word": "staccate il tempo", "meaning": "给出速度 / 进拍", "pos": "phrase"},
    {"word": "andamento", "meaning": "速度 / 走势", "pos": "n."},
    {"word": "rubato", "meaning": "弹性速度 / 散板", "pos": "adj./n."},
    {"word": "tenere", "meaning": "拉住 (时值) / 保持", "pos": "v."},
    {"word": "lasciare andare", "meaning": "放开 / 让声音流走", "pos": "phrase"},
    {"word": "coronamento", "meaning": "延长号 / 费马塔", "pos": "n."},
    {"word": "pausa", "meaning": "休止符", "pos": "n."},
    {"word": "respirare insieme", "meaning": "统一吸气", "pos": "phrase"},
    {"word": "ascoltatevi", "meaning": "互相比对听声音", "pos": "v. (refl.)"},
    {"word": "guardate me", "meaning": "看我 (指挥常用语)", "pos": "phrase"},
    {"word": "silenzio", "meaning": "安静", "pos": "n."},
    {"word": "da dove?", "meaning": "从哪里开始？", "pos": "phrase"},
    {"word": "da qui", "meaning": "从这里", "pos": "phrase"},
    {"word": "due battute prima", "meaning": "前两小节", "pos": "phrase"},
    {"word": "dopo la pausa", "meaning": "休止符之后", "pos": "phrase"},
    {"word": "alla fine", "meaning": "在最后", "pos": "phrase"},
    {"word": "leggero", "meaning": "轻巧的", "pos": "adj."},
    {"word": "pesante", "meaning": "笨重的", "pos": "adj."},
    {"word": "secco", "meaning": "干瘪的 / 干脆的", "pos": "adj."},
    {"word": "morbido", "meaning": "柔和的 / 有弹性的", "pos": "adj."},
    {"word": "dolce", "meaning": "温柔的", "pos": "adj."},
    {"word": "energico", "meaning": "有力的", "pos": "adj."},
    {"word": "subito", "meaning": "立刻", "pos": "adv."},
    {"word": "accento", "meaning": "重音", "pos": "n."},
    {"word": "sincope", "meaning": "切分音", "pos": "n."},
    {"word": "legatura", "meaning": "连线", "pos": "n."},
    {"word": "punto di valore", "meaning": "附点", "pos": "n."},
    {"word": "terzina", "meaning": "三连音", "pos": "n."},
    {"word": "quartina", "meaning": "四连音", "pos": "n."},
    {"word": "sotto voce", "meaning": "低声 / 窃窃私语般地唱", "pos": "adv."},
    {"word": "voce piena", "meaning": "全音量 / 真声唱", "pos": "n."},
    {"word": "ascolto", "meaning": "倾听", "pos": "n."},
    {"word": "intonazione di gruppo", "meaning": "声部音准", "pos": "n."},
    {"word": "equilibrio", "meaning": "平衡 (音量/音色)", "pos": "n."},
    {"word": "bilanciamento", "meaning": "天平 / 调配", "pos": "n."},
    {"word": "sfumatura", "meaning": "细微差别 / 渐变", "pos": "n."},
    {"word": "dinamica", "meaning": "力度变化", "pos": "n."},
    {"word": "sfogato", "meaning": "高亢的 / 宽广的", "pos": "adj."},
    {"word": "smorzando", "meaning": "逐渐消失", "pos": "adv."},
    {"word": "morendo", "meaning": "渐弱至无", "pos": "adv."},
    {"word": "perdendosi", "meaning": "音响渐渐隐去", "pos": "adv."},
    {"word": "calando", "meaning": "渐慢且渐弱", "pos": "adv."},
    {"word": "affrettando", "meaning": "急促地 / 渐快地", "pos": "adv."},
    {"word": "stringendo", "meaning": "加紧地 / 紧缩地", "pos": "adv."},
    {"word": "allargando", "meaning": "渐宽广且渐慢", "pos": "adv."},
    {"word": "largamente", "meaning": "宽广地", "pos": "adv."},
    {"word": "grave", "meaning": "庄严的 / 沉重的", "pos": "adj."},
    {"word": "adagio", "meaning": "柔板", "pos": "adv."},
    {"word": "andante", "meaning": "行板", "pos": "adv."},
    {"word": "moderato", "meaning": "中板", "pos": "adv."},
    {"word": "allegro", "meaning": "快板", "pos": "adv."},
    {"word": "presto", "meaning": "急板", "pos": "adv."},
    {"word": "vivace", "meaning": "活泼的快板", "pos": "adj./adv."},
    {"word": "tempo primo", "meaning": "回原速", "pos": "phrase"},
    {"word": "solista", "meaning": "独唱家 / 独奏家", "pos": "n."},
    {"word": "accompagnamento", "meaning": "伴奏", "pos": "n."},

    # === 二、声乐生理、玄学技巧与教授黑话 ===
    {"word": "respiro", "meaning": "呼吸", "pos": "n."},
    {"word": "fiato", "meaning": "气息", "pos": "n."},
    {"word": "inspirazione", "meaning": "吸气", "pos": "n."},
    {"word": "espirazione", "meaning": "呼气", "pos": "n."},
    {"word": "sostegno", "meaning": "气息支持 (横向力)", "pos": "n."},
    {"word": "appoggio", "meaning": "气息支点 (对抗力/靠)", "pos": "n."},
    {"word": "diaframma", "meaning": "横膈膜", "pos": "n."},
    {"word": "intercostale", "meaning": "肋间肌", "pos": "adj./n."},
    {"word": "addome", "meaning": "腹部", "pos": "n."},
    {"word": "laringe", "meaning": "喉头", "pos": "n."},
    {"word": "laringe bassa", "meaning": "低喉头", "pos": "n."},
    {"word": "faringe", "meaning": "咽腔", "pos": "n."},
    {"word": "gola", "meaning": "喉咙", "pos": "n."},
    {"word": "gola aperta", "meaning": "打开喉咙", "pos": "phrase"},
    {"word": "gola stretta", "meaning": "卡喉咙 / 喉咙紧", "pos": "phrase"},
    {"word": "corde vocali", "meaning": "声带", "pos": "n."},
    {"word": "glottide", "meaning": "声门", "pos": "n."},
    {"word": "colpo di glottide", "meaning": "声门冲击 / 喷音", "pos": "n."},
    {"word": "epiglottide", "meaning": "会厌", "pos": "n."},
    {"word": "palato molle", "meaning": "软腭", "pos": "n."},
    {"word": "ugola", "meaning": "小舌 / 悬雍垂", "pos": "n."},
    {"word": "lingua", "meaning": "舌头", "pos": "n."},
    {"word": "radice della lingua", "meaning": "舌根", "pos": "n."},
    {"word": "lingua tesa", "meaning": "舌根紧张", "pos": "phrase"},
    {"word": "mascella", "meaning": "下巴 / 颌", "pos": "n."},
    {"word": "mascella rilassata", "meaning": "放松下巴", "pos": "phrase"},
    {"word": "denti", "meaning": "牙齿", "pos": "n."},
    {"word": "labbra", "meaning": "嘴唇", "pos": "n."},
    {"word": "risonanza", "meaning": "共鸣", "pos": "n."},
    {"word": "maschera", "meaning": "面罩共鸣", "pos": "n."},
    {"word": "cavità orale", "meaning": "口腔", "pos": "n."},
    {"word": "cavità nasale", "meaning": "鼻腔", "pos": "n."},
    {"word": "seni frontali", "meaning": "额窦", "pos": "n."},
    {"word": "chiaroscuro", "meaning": "明暗平衡 / 完美共鸣", "pos": "n."},
    {"word": "squillo", "meaning": "穿透力 / 泛音金属亮光", "pos": "n."},
    {"word": "proiezione", "meaning": "声音投射 / 传远度", "pos": "n."},
    {"word": "registro", "meaning": "声区", "pos": "n."},
    {"word": "registro di petto", "meaning": "胸声区", "pos": "n."},
    {"word": "registro di testa", "meaning": "头声区", "pos": "n."},
    {"word": "registro misto", "meaning": "混声区", "pos": "n."},
    {"word": "falsetto", "meaning": "假声", "pos": "n."},
    {"word": "passaggio", "meaning": "换声点 / 换声区", "pos": "n."},
    {"word": "timbro", "meaning": "音色", "pos": "n."},
    {"word": "colore", "meaning": "色彩 / 音色倾向", "pos": "n."},
    {"word": "brillante", "meaning": "明亮的", "pos": "adj."},
    {"word": "scuro", "meaning": "暗的 / 浑厚的", "pos": "adj."},
    {"word": "chiaro", "meaning": "清脆的 / 发白的", "pos": "adj."},
    {"word": "bianco", "meaning": "苍白的 (指声音没有掩盖、大白声)", "pos": "adj."},
    {"word": "ingolato", "meaning": "吞进去的 (声音卡在喉咙里)", "pos": "adj."},
    {"word": "indietro", "meaning": "靠后的 (声音没有位置)", "pos": "adj./adv."},
    {"word": "avanti", "meaning": "靠前的 (声音位置好)", "pos": "adj./adv."},
    {"word": "nasale", "meaning": "鼻音重的 / 哼唧的", "pos": "adj."},
    {"word": "aria nel fiato", "meaning": "漏气 / 声音带漏气声", "pos": "phrase"},
    {"word": "suono fisso", "meaning": "直音 (没有颤音/僵硬)", "pos": "n."},
    {"word": "oscillazione", "meaning": "声音摇晃 / 颤音过大", "pos": "n."},
    {"word": "vibrato", "meaning": "健康的自然颤音", "pos": "n."},
    {"word": "emissione", "meaning": "通道 / 声音流出", "pos": "n."},
    {"word": "attacco", "meaning": "起音", "pos": "n."},
    {"word": "attacco duro", "meaning": "硬起音", "pos": "n."},
    {"word": "attacco morbido", "meaning": "软起音", "pos": "n."},
    {"word": "fonazione", "meaning": "发声", "pos": "n."},
    {"word": "articolazione", "meaning": "咬字咬弦器官动作", "pos": "n."},
    {"word": "dizione", "meaning": "吐字 / 咬字正音", "pos": "n."},
    {"word": "pronuncia", "meaning": "发音", "pos": "n."},
    {"word": "vocale", "meaning": "元音", "pos": "n."},
    {"word": "consonante", "meaning": "辅音", "pos": "n."},
    {"word": "intonazione", "meaning": "音准", "pos": "n."},
    {"word": "calante", "meaning": "音偏低", "pos": "adj."},
    {"word": "crescente", "meaning": "音偏高", "pos": "adj."},
    {"word": "stonato", "meaning": "跑调", "pos": "adj."},
    {"word": "intonato", "meaning": "音准准确", "pos": "adj."},
    {"word": "aprire", "meaning": "打开", "pos": "v."},
    {"word": "chiudere", "meaning": "关闭", "pos": "v."},
    {"word": "coprire", "meaning": "声音掩盖 (高声区换声技术)", "pos": "v."},
    {"word": "sostenere", "meaning": "托住 / 支持", "pos": "v."},
    {"word": "rilassare", "meaning": "放松", "pos": "v."},
    {"word": "tendere", "meaning": "拉紧 / 绷紧", "pos": "v."},
    {"word": "postura", "meaning": "站姿 / 唱歌体态", "pos": "n."},
    {"word": "messa di voce", "meaning": "渐强渐弱发声控制", "pos": "phrase"},
    {"word": "portamento", "meaning": "滑音", "pos": "n."},
    {"word": "copertura", "meaning": "声音掩盖技术", "pos": "n."},
    {"word": "filato", "meaning": "拉丝音 / 极弱的高音长线条", "pos": "n."},
    {"word": "impostazione", "meaning": "发声位置确定", "pos": "n."},
    {"word": "trillo", "meaning": "颤音 (花腔装饰音)", "pos": "n."},
    {"word": "fioritura", "meaning": "花腔装饰", "pos": "n."},
    {"word": "coloratura", "meaning": "花腔", "pos": "n."},
    {"word": "agilità", "meaning": "跑音灵活性", "pos": "n."},
    {"word": "legare", "meaning": "连贯", "pos": "v."},
    {"word": "spingere", "meaning": "硬推 / 猛冲气息 (唱歌大忌)", "pos": "v."},
    {"word": "suono schiacciato", "meaning": "被压扁的声音", "pos": "phrase"},
    {"word": "gola libera", "meaning": "释放喉咙 / 喉咙自由", "pos": "phrase"},
    {"word": "verticale", "meaning": "垂直的 (位置空间向上)", "pos": "adj."},
    {"word": "orizzontale", "meaning": "扁平的 / 横向的 (声音大忌)", "pos": "adj."},
    {"word": "affondare", "meaning": "使声音沉下去", "pos": "v."},
    {"word": "galleggiare", "meaning": "让声音飘在气息上", "pos": "v."},
    {"word": "leggerezza", "meaning": "轻盈感", "pos": "n."},
    {"word": "volume", "meaning": "音量", "pos": "n."},
    {"word": "corpo", "meaning": "声音的厚度 / 身体", "pos": "n."},

    # === 三、剧院舞台、演员调度与导演指令 ===
    {"word": "palcoscenico", "meaning": "舞台", "pos": "n."},
    {"word": "quinta", "meaning": "侧幕", "pos": "n."},
    {"word": "sipario", "meaning": "大幕", "pos": "n."},
    {"word": "scena", "meaning": "场景 / 场", "pos": "n."},
    {"word": "fondale", "meaning": "天幕 / 背景", "pos": "n."},
    {"word": "destra", "meaning": "右边", "pos": "n./adj."},
    {"word": "sinistra", "meaning": "左边", "pos": "n./adj."},
    {"word": "centro", "meaning": "舞台中央", "pos": "n."},
    {"word": "avanti", "meaning": "舞台前方 (靠近观众席)", "pos": "adv."},
    {"word": "indietro", "meaning": "舞台后方 (靠近天幕)", "pos": "adv."},
    {"word": "proscenio", "meaning": "前台 / 乐池前沿", "pos": "n."},
    {"word": "buca dell'orchestra", "meaning": "乐池", "pos": "n."},
    {"word": "golfo mistico", "meaning": "乐池 (神秘海湾)", "pos": "n."},
    {"word": "platea", "meaning": "一楼观众席 / 正厅", "pos": "n."},
    {"word": "palco", "meaning": "包厢", "pos": "n."},
    {"word": "loggione", "meaning": "顶层看台", "pos": "n."},
    {"word": "camerino", "meaning": "后台化妆间", "pos": "n."},
    {"word": "quinte", "meaning": "侧台幕布后", "pos": "n. pl."},
    {"word": "entrare", "meaning": "上场", "pos": "v."},
    {"word": "uscire", "meaning": "下场", "pos": "v."},
    {"word": "camminare", "meaning": "行走", "pos": "v."},
    {"word": "sedersi", "meaning": "坐下", "pos": "v."},
    {"word": "alzarsi", "meaning": "站起", "pos": "v."},
    {"word": "girarsi", "meaning": "转身", "pos": "v."},
    {"word": "inginocchiarsi", "meaning": "下跪 (歌剧名场面常用)", "pos": "v."},
    {"word": "sdraiarsi", "meaning": "躺下 (如茶花女临终)", "pos": "v."},
    {"word": "guardare il pubblico", "meaning": "面向观众", "pos": "phrase"},
    {"word": "spalle al pubblico", "meaning": "背对观众", "pos": "phrase"},
    {"word": "profilo", "meaning": "侧脸面向观众", "pos": "n."},
    {"word": "interazione", "meaning": "舞台对手戏互动", "pos": "n."},
    {"word": "regista", "meaning": "导演", "pos": "n."},
    {"word": "direttore", "meaning": "指挥", "pos": "n."},
    {"word": "maestro collaboratore", "meaning": "声乐指导老师", "pos": "n."},
    {"word": "pianista repetiteur", "meaning": "钢伴排练老师", "pos": "n."},
    {"word": "scenografo", "meaning": "舞美设计", "pos": "n."},
    {"word": "costumista", "meaning": "服装师", "pos": "n."},
    {"word": "direttore di scena", "meaning": "舞台监督", "pos": "n."},
    {"word": "suggeritore", "meaning": "提示嘴子 / 提词员", "pos": "n."},
    {"word": "buca del suggeritore", "meaning": "舞台前方的提词小洞", "pos": "n."},
    {"word": "luce", "meaning": "灯光", "pos": "n."},
    {"word": "riflettore", "meaning": "追光灯", "pos": "n."},
    {"word": "oscurità", "meaning": "全黑 / 暗场", "pos": "n."},
    {"word": "buio pesto", "meaning": "漆黑一片", "pos": "n."},
    {"word": "illuminazione", "meaning": "采光 / 照明", "pos": "n."},
    {"word": "soprano", "meaning": "女高音", "pos": "n."},
    {"word": "tenore", "meaning": "男高音", "pos": "n."},
    {"word": "baritono", "meaning": "男中音", "pos": "n."},
    {"word": "mezzosoprano", "meaning": "女中音", "pos": "n."},
    {"word": "basso", "meaning": "男低音", "pos": "n."},
    {"word": "contralto", "meaning": "女低音", "pos": "n."},
    {"word": "comprimario", "meaning": "配角 / 二手角色", "pos": "n."},
    {"word": "corista", "meaning": "合唱队员", "pos": "n."},
    {"word": "comparse", "meaning": "群众演员 / 龙套", "pos": "n. pl."},
    {"word": "prova di regia", "meaning": "导演戏剧排练", "pos": "n."},
    {"word": "prova all'italiana", "meaning": "音乐坐排 (不带动作带乐队)", "pos": "n."},
    {"word": "antegenerale", "meaning": "预总排练 (倒数第二次)", "pos": "n."},
    {"word": "trucco", "meaning": "化妆", "pos": "n."},
    {"word": "parrucca", "meaning": "假发", "pos": "n."},
    {"word": "costume", "meaning": "演出服", "pos": "n."},
    {"word": "scenografia", "meaning": "舞台道具布景", "pos": "n."},
    {"word": "attrezzeria", "meaning": "舞台小道具", "pos": "n."},
    {"word": "atto", "meaning": "幕", "pos": "n."},
    {"word": "quadro", "meaning": "场 / 幅", "pos": "n."},
    {"word": "applauso", "meaning": "掌声", "pos": "n."},
    {"word": "inchino", "meaning": "鞠躬谢幕", "pos": "n."},
    {"word": "fischio", "meaning": "喝倒彩 / 嘘声", "pos": "n."},
    {"word": "bis", "meaning": "再来一个 / 返场唱", "pos": "int."},
    {"word": "debutto", "meaning": "首演 / 登台", "pos": "n."},
    {"word": "recita", "meaning": "演出场次", "pos": "n."},

    # === 四、乐谱、和弦分析与史论基础 ===
    {"word": "spartito", "meaning": "声乐谱 / 钢琴伴奏谱", "pos": "n."},
    {"word": "partitura", "meaning": "乐队总谱", "pos": "n."},
    {"word": "parte", "meaning": "分谱 / 声部", "pos": "n."},
    {"word": "pagina", "meaning": "页码", "pos": "n."},
    {"word": "riga", "meaning": "一行谱", "pos": "n."},
    {"word": "sistema", "meaning": "大谱表", "pos": "n."},
    {"word": "battuta", "meaning": "小节", "pos": "n."},
    {"word": "misura", "meaning": "拍号 / 小节", "pos": "n."},
    {"word": "sezione", "meaning": "音乐段落", "pos": "n."},
    {"word": "frase", "meaning": "乐句", "pos": "n."},
    {"word": "periodo", "meaning": "乐段", "pos": "n."},
    {"word": "introduzione", "meaning": "前奏 / 引子", "pos": "n."},
    {"word": "coda", "meaning": "尾声", "pos": "n."},
    {"word": "finale", "meaning": "终曲", "pos": "n."},
    {"word": "nota", "meaning": "音符", "pos": "n."},
    {"word": "altezza", "meaning": "音高", "pos": "n."},
    {"word": "intervallo", "meaning": "音程", "pos": "n."},
    {"word": "scala", "meaning": "音阶", "pos": "n."},
    {"word": "semitono", "meaning": "半音", "pos": "n."},
    {"word": "tono", "meaning": "全音", "pos": "n."},
    {"word": "accordo", "meaning": "和弦", "pos": "n."},
    {"word": "tonalità", "meaning": "调性", "pos": "n."},
    {"word": "tonica", "meaning": "主音", "pos": "n."},
    {"word": "dominante", "meaning": "属音", "pos": "n."},
    {"word": "sottodominante", "meaning": "下属音", "pos": "n."},
    {"word": "modulazione", "meaning": "转调", "pos": "n."},
    {"word": "cadenza", "meaning": "终止式 / 华彩", "pos": "n."},
    {"word": "cadenza d'inganno", "meaning": "阻碍终止", "pos": "n."},
    {"word": "metro", "meaning": "拍子结构", "pos": "n."},
    {"word": "ritmo", "meaning": "节奏", "pos": "n."},
    {"word": "tempo composto", "meaning": "复拍子", "pos": "n."},
    {"word": "tempo semplice", "meaning": "单拍子", "pos": "n."},
    {"word": "forma", "meaning": "曲式", "pos": "n."},
    {"word": "tema", "meaning": "主题", "pos": "n."},
    {"word": "variazione", "meaning": "变奏", "pos": "n."},
    {"word": "sviluppo", "meaning": "展开部", "pos": "n."},
    {"word": "ripresa", "meaning": "再现部", "pos": "n."},
    {"word": "recitativo", "meaning": "宣叙调", "pos": "n."},
    {"word": "recitativo secco", "meaning": "清宣叙调 (通常只有羽管键琴伴奏)", "pos": "n."},
    {"word": "recitativo accompagnato", "meaning": "伴奏宣叙调", "pos": "n."},
    {"word": "arioso", "meaning": "咏叙调", "pos": "n."},
    {"word": "aria", "meaning": "咏叹调", "pos": "n."},
    {"word": "romanza", "meaning": "浪漫曲", "pos": "n."},
    {"word": "duetto", "meaning": "二重唱", "pos": "n."},
    {"word": "terzetto", "meaning": "三重唱", "pos": "n."},
    {"word": "quartetto", "meaning": "四重唱", "pos": "n."},
    {"word": "coro", "meaning": "合唱", "pos": "n."},
    {"word": "ouverture", "meaning": "序曲", "pos": "n."},
    {"word": "cabaletta", "meaning": "卡巴列塔", "pos": "n."},
    {"word": "stretta", "meaning": "紧板", "pos": "n."},
    {"word": "lied", "meaning": "艺术歌曲", "pos": "n."},
    {"word": "canzone", "meaning": "歌曲", "pos": "n."},
    {"word": "barocco", "meaning": "巴洛克", "pos": "n./adj."},
    {"word": "classico", "meaning": "古典", "pos": "n./adj."},
    {"word": "romantico", "meaning": "浪漫", "pos": "n./adj."},
    {"word": "verista", "meaning": "真实主义的", "pos": "adj."},
    {"word": "contemporaneo", "meaning": "当代的", "pos": "adj."},
    {"word": "bel canto", "meaning": "美声唱法时期/风格", "pos": "n."},
    {"word": "opera buffa", "meaning": "喜歌剧", "pos": "n."},
    {"word": "opera seria", "meaning": "正歌剧", "pos": "n."},
    {"word": "verismo", "meaning": "真实主义", "pos": "n."},
    {"word": "compositore", "meaning": "作曲家", "pos": "n."},
    {"word": "repertorio", "meaning": "保留曲目", "pos": "n."},
    {"word": "stile", "meaning": "风格", "pos": "n."},
    {"word": "analisi", "meaning": "分析", "pos": "n."},
    {"word": "struttura", "meaning": "结构", "pos": "n."},
    {"word": "armonia", "meaning": "和声学", "pos": "n."},
    {"word": "melodia", "meaning": "旋律", "pos": "n."},
    {"word": "contrappunto", "meaning": "对位法", "pos": "n."},
    {"word": "Medioevo", "meaning": "中世纪", "pos": "n."},
    {"word": "Rinascimento", "meaning": "文艺复兴", "pos": "n."},
    {"word": "Classicismo", "meaning": "古典主义", "pos": "n."},
    {"word": "Romanticismo", "meaning": "浪漫主义", "pos": "n."},
    {"word": "Novecento", "meaning": "20世纪", "pos": "n."},
    {"word": "orchestrazione", "meaning": "配器法", "pos": "n."},
    {"word": "chiave", "meaning": "谱号", "pos": "n."},
    {"word": "chiave di violino", "meaning": "高音谱号 (G谱号)", "pos": "n."},
    {"word": "chiave di basso", "meaning": "低音谱号 (F谱号)", "pos": "n."},
    {"word": "chiave di contralto", "meaning": "中音谱号 (C谱号)", "pos": "n."},
    {"word": "alterazione", "meaning": "变音记号", "pos": "n."},
    {"word": "diesis", "meaning": "升号 (#)", "pos": "n."},
    {"word": "bemolle", "meaning": "降号 (b)", "pos": "n."},
    {"word": "bequadro", "meaning": "还原号", "pos": "n."},
    {"word": "maggiore", "meaning": "大调的", "pos": "adj."},
    {"word": "minore", "meaning": "小调的", "pos": "adj."},

    # === 五、音乐学院行政、秘书处周旋与高频生存短句 ===
    {"word": "iscrizione", "meaning": "注册 / 报名", "pos": "n."},
    {"word": "immatricolazione", "meaning": "正式入学注册", "pos": "n."},
    {"word": "ammissione", "meaning": "录取", "pos": "n."},
    {"word": "audizione", "meaning": "听音 / 试唱 / 面试", "pos": "n."},
    {"word": "diploma", "meaning": "文凭 / 毕业证", "pos": "n."},
    {"word": "corso", "meaning": "课程 / 专业", "pos": "n."},
    {"word": "lezione", "meaning": "课", "pos": "n."},
    {"word": "seminario", "meaning": "研讨会 / 讲座", "pos": "n."},
    {"word": "laboratorio", "meaning": "实践课 / 工作坊", "pos": "n."},
    {"word": "masterclass", "meaning": "大师班", "pos": "n."},
    {"word": "esame", "meaning": "考试", "pos": "n."},
    {"word": "valutazione", "meaning": "成绩评估", "pos": "n."},
    {"word": "commissione", "meaning": "考官委员会 / 评委", "pos": "n."},
    {"word": "modulo", "meaning": "纸质表格", "pos": "n."},
    {"word": "domanda", "meaning": "申请书 / 问题", "pos": "n."},
    {"word": "certificato", "meaning": "官方证明", "pos": "n."},
    {"word": "documento", "meaning": "身份证件 / 文件", "pos": "n."},
    {"word": "credito", "meaning": "学分 (CFA)", "pos": "n."},
    {"word": "frequenza", "meaning": "出勤率", "pos": "n."},
    {"word": "obbligatorio", "meaning": "必修的", "pos": "adj."},
    {"word": "facoltativo", "meaning": "选修的", "pos": "adj."},
    {"word": "tesi", "meaning": "毕业论文", "pos": "n."},
    {"word": "dissertazione", "meaning": "论文阐述", "pos": "n."},
    {"word": "ricerca", "meaning": "研究", "pos": "n."},
    {"word": "concorso", "meaning": "国际比赛 / 选拔赛", "pos": "n."},
    {"word": "borsa di studio", "meaning": "奖学金", "pos": "n."},
    {"word": "biblioteca", "meaning": "图书馆", "pos": "n."},
    {"word": "prestito", "meaning": "借书 / 借谱", "pos": "n."},
    {"word": "catalogo", "meaning": "目录检索", "pos": "n."},
    {"word": "segreteria", "meaning": "秘书处", "pos": "n."},
    {"word": "tasse", "meaning": "学费 / 税", "pos": "n. pl."},
    {"word": "esonero", "meaning": "免除 (学费减免)", "pos": "n."},
    {"word": "ISEE", "meaning": "家庭经济综合状况证明", "pos": "n."},
    {"word": "permesso di soggiorno", "meaning": "居留许可证", "pos": "n."},
    {"word": "ricevuta", "meaning": "收据 / 居留小条", "pos": "n."},
    {"word": "libretto", "meaning": "学生证 / 选课本", "pos": "n."},
    {"word": "prenotazione", "meaning": "预约 (考试/琴房)", "pos": "n."},
    {"word": "aula", "meaning": "教室", "pos": "n."},
    {"word": "aula da concerto", "meaning": "音乐厅 / 演奏厅", "pos": "n."},
    {"word": "pianoforte a coda", "meaning": "三角钢琴", "pos": "n."},
    {"word": "pianoforte verticale", "meaning": "立式钢琴", "pos": "n."},
    {"word": "chiave dell'aula", "meaning": "教室钥匙", "pos": "n."},
    {"word": "orario", "meaning": "课表 / 时间表", "pos": "n."},
    {"word": "ricevimento docenti", "meaning": "教授答疑时间", "pos": "n."},
    {"word": "assenza", "meaning": "缺勤", "pos": "n."},
    {"word": "giustificazione", "meaning": "请假条 / 正当理由", "pos": "n."},
    {"word": "appello d'esame", "meaning": "考试期 / 考试批次", "pos": "n."},
    {"word": "bocciato", "meaning": "被挂科 / 没通过", "pos": "adj."},
    {"word": "promosso", "meaning": "通过考试", "pos": "adj."},
    {"word": "trenta e lode", "meaning": "30分加赞扬 (满分)", "pos": "n."},
    {"word": "coordinatore", "meaning": "系主任", "pos": "n."},
    {"word": "direttore del conservatorio", "meaning": "音乐学院院长", "pos": "n."},
    {"word": "maestro", "meaning": "大师 / 对教授的尊称", "pos": "n."}
]
